theme: theme
title: Symbolic
author: Jason Morley
email: support@jbmorley.co.uk
description: Icon Designer
baseurl: ""
url: "https://symbolic.jbmorley.co.uk"
repository: https://github.com/inseven/symbolic
copyright: 2022-2026 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

navigation:
  - title: Symbolic
    href: /
  - title: App Store
    href: https://apps.apple.com/us/app/id6477066265
  - title: Releases
    href: /releases
  - title: Source
    href: https://github.com/inseven/symbolic
  - title: More
    href: https://jbmorley.co.uk/software/
  - title: Donate ❤️
    href: https://jbmorley.co.uk/support/

footer:
  - title: Privacy Policy
    href: /privacy-policy
  - title: Support
    href: /support
  - title: License
    href: /license

destination: ../_site

toc:
  ordered_list: true

gfm_admonitions:
  inject_css: false

defaults:
  - values:
      layout: "page"
  - scope:
      path: "docs"
    values:
      layout: "documentation"
      toc: true
      shows_title: true
