theme: theme
title: Symbolic
author: Jason Morley
email: support@jbmorley.co.uk
description: Icon Designer
baseurl: ""
url: "https://symbolic.jbmorley.co.uk"
repository: https://github.com/inseven/symbolic
copyright: 2022-2026 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

navigation:
  - title: Symbolic
    href: /
  - title: Releases
    href: /releases
  - title: GitHub
    href: https://github.com/inseven/symbolic
  - title: More
    href: https://jbmorley.co.uk/software/
  - title: Donate ❤️
    href: https://jbmorley.co.uk/support/

footer:
  - title: Privacy Policy
    href: /privacy-policy
  - title: Support
    href: /support
  - title: License
    href: /license

destination: ../_site

defaults:
  - values:
      layout: "page"
